project:
  type: website
  output-dir: docs

website:
  title: "Magdalena Lederbauer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 'assets/files/cv.pdf'
        text: CV
      - href: portfolio/portfolio.qmd
        text: Portfolio
      - href: press.qmd
        text: Press
      # - href: https://bytesizedchem.com
      #   text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

execute:
  freeze: auto


