---
title: "Portfolio"
---

* [2024] Feature *Frau des Monats, März 2024* (DE). Woman of the month, March 2024, at my former high school. Highlighting young women in STEM, initiated by my high school, Wiedner Gymnasium – Sir Karl Popper Schule

* [2024] [Article Niederösterreichische Nachrichten (DE)](https://m.noen.at/moedling/akademische-karriere-magdalena-lederbauer-von-zuerich-geht-es-jetzt-nach-massachusetts-405350141) About my master studies.

* [2023] [Portrait by the Austrian Academy of Sciences Study Foundation (DE)](https://www.oeaw.ac.at/studienstiftung/portraet/magdalena-lederbauer-eine-empfehlung-fuer-die-studienstiftung-aus-der-eth-zuerich)

* [2023] [Get to know the new excellence scholarship holders at D-CHAB (EN/DE)](https://chab.ethz.ch/news-und-veranstaltungen/d-chab-news/2023/11/fuenf-neue-exzellenz-stipendiatinnen-am-d-chab-stellen-sich-vor.html). Feature of the excellence scholarship holders of the department of chemistry and applied biosciences at ETH Zurich. I highlight what motivates me about my studies and science!

* [2023] [Article about our involvement as authors of the International Chemistry Olympiad in Switzerland (EN/DE)](https://chab.ethz.ch/en/news-and-events/d-chab-news/2023/03/icho-the-connecting-power-of-chemistry.html)

* [2023] [Portrait of the authors of the IChO 2023 Catalyzer](https://www.icho2023.ch/post/our-student-authors) I am super proud of our science commumnication team!

* [2023] [Podcast FM4 Anfang 20 (DE)](https://podcasts.apple.com/ch/podcast/fm4-anfang-20/id1576152788?i=1000609335072) Podcast episode by the Austrian radio network FM4 on my experiences as a gifted student a school for gifted students

* [2022] [Feature of the scholarship holders of the excellence program of studies abroad by Lower Austria](https://www.meinbezirk.at/gaenserndorf/c-lokales/sinfonie-in-graffiti-utopien-werden-wirklichkeit_a5258014)

* [2021] [Article Niederösterreichische Nachrichten (DE)](https://m.noen.at/moedling/vorzeigestudentin-magdalena-lederbauer-das-chemie-talent-aus-kaltenleutgeb-kaltenleutgeben-eth-zuerich-magdalena-lederbauer-print-295339999)

* [2020] [Article NÖN (DE)](https://m.noen.at/moedling/zuerich-kaltenleutgeben-studium-in-zuerich-chemie-bleibt-nr-1-kaltenleutgeben-magdalena-lederbauer-chemie-bildung-print-238865818)

* [2020] Club Alpbach Scholarship for the Lower Austrian cohort. Due to COVID-19 outbreak held in Lower Austria. With 18 years old the youngest of 20 scholarship holders.

* [2020] Podcast (DE) [Podcast about gifted education](https://www.popperschule.at/begabungsfoerderung/beste-koepfe-der-podcast-fuer-talentefoerderung-und-hochbegabung/) An interview of me as a former student of the Sir Karl Popper Schule as well as a successful "chemistry olympian". I am giving detailed insights into everyday school life at the Sir Karl Popper Schule, tells what makes it a special school for me and reveal why the best gingerbread spice recipe has something to do with science!

* [2019] [Jump-start into science, ORF (DE)](https://wien.orf.at/v2/news/stories/2981444/)

* [2019] [25 talents that will change your business model (DE)](https://industriemagazin.at/artikel/generation-greta-25-talente-die-ihr-geschaeftsmodell-veraendern/) I was featured by one of the leading industry magazines in Austria during my time as an "olympian" in the chemistry olympiad.

* [2019] [Feature of the training for the European Science Olympiad 2019](https://www.lakeside-scitec.com/en/news/news/news-detail/euso-trainingstage-im-educational-lab) I worked as a mentor and co-lead for chemistry in 2019. We are super proud for our team to have scored a gold and a bronze medal! 🎉

* [2019] [Feature by the PH NOE of the winners of the 2019 Austrian National Chemistry Olympiad](https://www.ph-noe.ac.at/de/news/news-detail/magdalena-lederbauer-ist-siegerin-der-oesterreichischen-chemie-olympiade)

* [2019] Article Wiener Zeitung (DE)

* [2019] [Feature by KURIER of the winners of the 2019 Austrian National Chemistry Olympiad](https://kurier.at/chronik/niederoesterreich/gold-fuer-nachwuchs-marie-curie/400514155)

* [2019] [Article Niederösterreichische Nachrichten (DE)](https://m.noen.at/moedling/kaltenleutgeben-chemie-talent-bei-olympia-kaltenleutgeben-magdalena-lederbauer-chemie-chemie-olympiade-143995382)

* [2019] [Feature *Wienerin des Monats, Juli 2019*. Viennese of the month, July 2019. (DE)](https://www.pressreader.com/austria/kronen-zeitung-9gf1/20190804/281908774762251)

* [2018] [Feature of the winning teams of the European Science Olympiad 2018](https://www.ph-kaernten.ac.at/aktuelles/detail/?tx_news_pi1%5Baction%5D=detail&tx_news_pi1%5Bcontroller%5D=News&tx_news_pi1%5Bnews%5D=339&cHash=f4260518d066fc2e1fc3094d248377a9) I am beyond proud and excited for our team!
<!-- https://m.noen.at/moedling/scienceolympiaden-sieg-kaltenleutgebnerin-holt-silbermedaille-magdalena-lederbauer-16-europaeische-scienceolympiade-93989625 -->

